# Generated by Django 6.0.2 on 2026-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
