# Generated by Django 6.0.5 on 2026-05-28 13:20

import uuid

import chat.models
from django.db import migrations, models


def _normalize_legacy_conversation_ids(apps, schema_editor):
    """Convert legacy numeric conversation IDs to real UUID strings before type conversion."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id FROM chat_conversation ORDER BY id')
        old_ids = [row[0] for row in cursor.fetchall()]

    old_to_new = {}
    for old_id in old_ids:
        try:
            uuid.UUID(str(old_id))
        except (ValueError, TypeError, AttributeError):
            old_to_new[str(old_id)] = str(uuid.uuid4())

    if not old_to_new:
        return

    with schema_editor.connection.cursor() as cursor:
        for old_id, new_id in old_to_new.items():
            cursor.execute(
                'UPDATE chat_message SET conversation_id = %s WHERE conversation_id = %s',
                [new_id, old_id],
            )
            cursor.execute(
                'UPDATE chat_conversation_participants SET conversation_id = %s WHERE conversation_id = %s',
                [new_id, old_id],
            )
            cursor.execute(
                'UPDATE chat_conversation SET id = %s WHERE id = %s',
                [new_id, old_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default=chat.models.generate_conversation_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.RunPython(_normalize_legacy_conversation_ids, migrations.RunPython.noop),
    ]
