# Generated by Django 6.0.5 on 2026-05-28 13:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_fix_legacy_conversation_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default=chat.models.generate_conversation_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
